// honeywell/apps/web/src/app/(main)/community/page.tsx
/**
 * @file 社区广场首页
 * @description 社交信息流布局，展示用户提现成功分享帖子
 * @route /community
 *
 * 设计要点：
 * - 卡片式信息流，双图预览（平台截图+收据截图）
 * - 浮动创建按钮
 * - 下拉刷新 + 无限滚动分页
 * - 点赞/评论交互
 */

'use client';

import { useState, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import { useQuery, useInfiniteQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { LazyMotion, domAnimation, m } from 'motion/react';
import {
  RiHeartFill,
  RiHeartLine,
  RiChat3Line,
  RiAddLine,
  RiArrowLeftSLine,
  RiTimeLine,
  RiShieldCheckFill,
  RiUserLine,
} from '@remixicon/react';
import { useText } from '@/hooks/use-text';
import { useGlobalConfig } from '@/hooks/use-global-config';
import { useAnimationConfig } from '@/hooks/use-animation-config';
import { SPRINGS, STAGGER } from '@/lib/animation';
import { formatCurrency } from '@/lib/format';
import { PullToRefresh } from '@/components/ui/pull-to-refresh';
import { InfiniteScrollTrigger } from '@/components/ui/infinite-scroll-trigger';
import { EmptyState } from '@/components/business/empty-state';
import { FloatingOrbs } from '@/components/effects/floating-orbs';
import api from '@/lib/api';

/** 帖子数据类型 */
interface Post {
  id: number;
  userId: number;
  userName: string;
  userAvatar: string | null;
  withdrawAmount: number;
  platformScreenshot: string;
  receiptScreenshot: string;
  content: string | null;
  likeCount: number;
  commentCount: number;
  isLiked: boolean;
  createdAt: string;
}

interface PostsResponse {
  list: Post[];
  pagination: {
    page: number;
    pageSize: number;
    total: number;
  };
}

/**
 * 社区广场首页
 */
export default function CommunityPage() {
  const router = useRouter();
  const t = useText();
  const { config } = useGlobalConfig();
  const { isAnimationEnabled } = useAnimationConfig();
  const queryClient = useQueryClient();

  // 无限滚动获取帖子列表
  const {
    data,
    isLoading,
    isError,
    fetchNextPage,
    hasNextPage,
    isFetchingNextPage,
    refetch,
  } = useInfiniteQuery({
    queryKey: ['community-posts'],
    queryFn: ({ pageParam = 1 }) =>
      api.get<PostsResponse>(`/community/posts?page=${pageParam}&pageSize=10`),
    getNextPageParam: (lastPage) => {
      const { page, pageSize, total } = lastPage.pagination;
      return page * pageSize < total ? page + 1 : undefined;
    },
    initialPageParam: 1,
  });

  const posts = data?.pages.flatMap((p) => p.list) ?? [];

  // 点赞/取消点赞
  const likeMutation = useMutation({
    mutationFn: (postId: number) =>
      api.post<{ liked: boolean; likeCount: number }>(`/community/posts/${postId}/like`),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['community-posts'] });
    },
  });

  const handleRefresh = useCallback(async () => {
    await refetch();
  }, [refetch]);

  // 加载骨架屏
  if (isLoading) {
    return <FeedSkeleton />;
  }

  // 错误状态
  if (isError) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-primary-50/60 via-white to-neutral-50">
        <FeedHeader />
        <div className="px-4 py-20">
          <EmptyState
            icon={<RiChat3Line className="size-12 text-neutral-400" />}
            title={t('error.load_failed')}
            description={t('error.try_again')}
            actionText={t('btn.retry')}
            onAction={() => refetch()}
          />
        </div>
      </div>
    );
  }

  return (
    <LazyMotion features={domAnimation}>
      <div className="relative min-h-screen bg-gradient-to-b from-primary-50/60 via-white to-neutral-50 overflow-hidden">
        <FloatingOrbs variant="activities" />
        <FeedHeader />

        <PullToRefresh onRefresh={handleRefresh}>
          {/* 页面标题区 */}
          <m.div
            initial={isAnimationEnabled ? { opacity: 0, y: -10 } : undefined}
            animate={{ opacity: 1, y: 0 }}
            transition={SPRINGS.gentle}
            className="relative z-10 px-4 pt-4 pb-2"
          >
            <h2 className="text-xl font-bold text-neutral-800">
              {t('community.title')}
            </h2>
            <p className="text-sm text-neutral-500 mt-0.5">
              {t('community.subtitle')}
            </p>
          </m.div>

          {/* 帖子信息流 */}
          <div className="relative z-10 px-4 pb-28 space-y-4">
            {posts.length === 0 ? (
              <EmptyState
                icon={<RiChat3Line className="size-12 text-neutral-400" />}
                title={t('community.empty')}
                description={t('community.empty_desc')}
              />
            ) : (
              posts.map((post, index) => (
                <PostCard
                  key={post.id}
                  post={post}
                  config={config}
                  t={t}
                  index={index}
                  isAnimationEnabled={isAnimationEnabled}
                  onLike={() => likeMutation.mutate(post.id)}
                  onDetail={() => router.push(`/community/${post.id}`)}
                />
              ))
            )}

            <InfiniteScrollTrigger
              hasMore={!!hasNextPage}
              isLoading={isFetchingNextPage}
              onLoadMore={() => fetchNextPage()}
            />
          </div>
        </PullToRefresh>

        {/* 浮动创建按钮 */}
        <m.button
          onClick={() => router.push('/community/create')}
          className="fixed bottom-32 right-5 z-40 flex items-center justify-center w-14 h-14 rounded-full bg-primary-500 text-white shadow-[0_6px_24px_rgba(var(--color-primary-rgb),0.4)]"
          whileHover={{ scale: 1.1 }}
          whileTap={{ scale: 0.9 }}
          transition={SPRINGS.snappy}
        >
          <RiAddLine className="size-7" />
        </m.button>
      </div>
    </LazyMotion>
  );
}

/** 顶部导航栏 */
function FeedHeader() {
  const router = useRouter();
  const t = useText();

  return (
    <header className="sticky top-0 z-30">
      <div
        style={{
          background: 'rgba(250,250,248,0.88)',
          backdropFilter: 'blur(20px) saturate(1.4)',
          WebkitBackdropFilter: 'blur(20px) saturate(1.4)',
          borderBottom: '1px solid rgba(0,0,0,0.04)',
        }}
      >
        <div className="flex items-center justify-between h-14 px-4">
          <button
            onClick={() => router.back()}
            className="p-2 -ml-2 rounded-xl hover:bg-neutral-100/80 active:scale-95 transition-all"
            aria-label={t('btn.back')}
          >
            <RiArrowLeftSLine className="w-6 h-6 text-neutral-600" />
          </button>
          <h1 className="text-lg font-bold text-neutral-800 tracking-tight">
            {t('nav.community')}
          </h1>
          <button
            onClick={() => router.push('/community/my')}
            className="p-2 -mr-2 rounded-xl hover:bg-neutral-100/80 active:scale-95 transition-all"
            aria-label={t('community.my_posts')}
          >
            <RiUserLine className="w-5 h-5 text-neutral-600" />
          </button>
        </div>
      </div>
    </header>
  );
}

/** 帖子卡片 */
function PostCard({
  post,
  config,
  t,
  index,
  isAnimationEnabled,
  onLike,
  onDetail,
}: {
  post: Post;
  config: ReturnType<typeof useGlobalConfig>['config'];
  t: ReturnType<typeof useText>;
  index: number;
  isAnimationEnabled: boolean;
  onLike: () => void;
  onDetail: () => void;
}) {
  const [liked, setLiked] = useState(post.isLiked);
  const [likeCount, setLikeCount] = useState(post.likeCount);

  const handleLike = (e: React.MouseEvent) => {
    e.stopPropagation();
    setLiked(!liked);
    setLikeCount((prev) => (liked ? prev - 1 : prev + 1));
    onLike();
  };

  // 格式化时间为相对时间
  const formatRelativeTime = (dateStr: string) => {
    const diff = Date.now() - new Date(dateStr).getTime();
    const minutes = Math.floor(diff / 60000);
    if (minutes < 1) return t('time.justNow');
    if (minutes < 60) return `${minutes} ${t('time.minutesAgo')}`;
    const hours = Math.floor(minutes / 60);
    if (hours < 24) return `${hours} ${t('time.hoursAgo')}`;
    const days = Math.floor(hours / 24);
    return `${days} ${t('time.daysAgo')}`;
  };

  return (
    <m.div
      initial={isAnimationEnabled ? { opacity: 0, y: 16 } : undefined}
      animate={{ opacity: 1, y: 0 }}
      transition={{ ...SPRINGS.gentle, delay: index * STAGGER.fast }}
      onClick={onDetail}
      className="bg-white rounded-2xl overflow-hidden shadow-[0_2px_12px_rgba(0,0,0,0.04)] border border-neutral-100/60 active:scale-[0.99] transition-transform cursor-pointer"
    >
      {/* 用户信息 + 金额标签 */}
      <div className="flex items-center justify-between px-4 pt-4 pb-2">
        <div className="flex items-center gap-3">
          {/* 头像 */}
          <div className="relative w-10 h-10 rounded-full bg-gradient-to-br from-primary-100 to-primary-200 flex items-center justify-center overflow-hidden ring-2 ring-primary-100/50">
            {post.userAvatar ? (
              <img
                src={post.userAvatar}
                alt={post.userName}
                className="w-full h-full object-cover"
              />
            ) : (
              <span className="text-sm font-bold text-primary-600">
                {post.userName?.charAt(0)?.toUpperCase()}
              </span>
            )}
            <div className="absolute -bottom-0.5 -right-0.5 w-4 h-4 rounded-full bg-primary-500 border-2 border-white flex items-center justify-center">
              <RiShieldCheckFill className="size-2.5 text-white" />
            </div>
          </div>
          <div>
            <p className="text-sm font-semibold text-neutral-800">{post.userName}</p>
            <div className="flex items-center gap-1 text-xs text-neutral-400">
              <RiTimeLine className="size-3" />
              <span>{formatRelativeTime(post.createdAt)}</span>
            </div>
          </div>
        </div>

        {/* 提现金额标签 */}
        <div className="flex items-center gap-1 px-3 py-1.5 rounded-full bg-gradient-to-r from-primary-50 to-primary-100 border border-primary-200/50">
          <span className="text-xs font-bold text-primary-600">
            {formatCurrency(post.withdrawAmount, config)}
          </span>
        </div>
      </div>

      {/* 双图预览 */}
      <div className="grid grid-cols-2 gap-2 px-4 py-2">
        <div className="relative aspect-[4/3] rounded-xl overflow-hidden bg-neutral-100">
          <img
            src={post.platformScreenshot}
            alt={t('community.platform_screenshot')}
            className="w-full h-full object-cover"
            loading="lazy"
          />
          <div className="absolute bottom-1.5 left-1.5 px-2 py-0.5 rounded-md bg-black/50 backdrop-blur-sm">
            <span className="text-[10px] text-white font-medium">
              {t('community.platform')}
            </span>
          </div>
        </div>
        <div className="relative aspect-[4/3] rounded-xl overflow-hidden bg-neutral-100">
          <img
            src={post.receiptScreenshot}
            alt={t('community.receipt_screenshot')}
            className="w-full h-full object-cover"
            loading="lazy"
          />
          <div className="absolute bottom-1.5 left-1.5 px-2 py-0.5 rounded-md bg-black/50 backdrop-blur-sm">
            <span className="text-[10px] text-white font-medium">
              {t('community.receipt')}
            </span>
          </div>
        </div>
      </div>

      {/* 文本内容 */}
      {post.content && (
        <p className="px-4 pb-2 text-sm text-neutral-600 line-clamp-2">
          {post.content}
        </p>
      )}

      {/* 互动栏 */}
      <div className="flex items-center justify-between px-4 py-3 border-t border-neutral-50">
        <button
          onClick={handleLike}
          className="flex items-center gap-1.5 group"
        >
          <m.div
            animate={liked ? { scale: [1, 1.3, 1] } : { scale: 1 }}
            transition={SPRINGS.bouncy}
          >
            {liked ? (
              <RiHeartFill className="size-5 text-red-500" />
            ) : (
              <RiHeartLine className="size-5 text-neutral-400 group-hover:text-red-400 transition-colors" />
            )}
          </m.div>
          <span className={`text-sm tabular-nums ${liked ? 'text-red-500 font-medium' : 'text-neutral-400'}`}>
            {likeCount}
          </span>
        </button>

        <div className="flex items-center gap-1.5 text-neutral-400">
          <RiChat3Line className="size-5" />
          <span className="text-sm tabular-nums">{post.commentCount}</span>
        </div>
      </div>
    </m.div>
  );
}

/** 加载骨架屏 */
function FeedSkeleton() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-primary-50/60 via-white to-neutral-50">
      <header className="sticky top-0 z-30" style={{ background: 'rgba(250,250,248,0.88)', backdropFilter: 'blur(20px)' }}>
        <div className="flex items-center justify-between h-14 px-4">
          <div className="w-10 h-10 bg-neutral-200/60 rounded-lg animate-pulse" />
          <div className="w-24 h-5 bg-neutral-200/60 rounded animate-pulse" />
          <div className="w-10 h-10 bg-neutral-200/60 rounded-lg animate-pulse" />
        </div>
      </header>
      <div className="px-4 pt-4 space-y-4">
        <div className="h-7 w-20 bg-neutral-200/60 rounded animate-pulse" />
        <div className="h-4 w-48 bg-neutral-200/40 rounded animate-pulse" />
        {Array.from({ length: 3 }).map((_, i) => (
          <div key={i} className="bg-white rounded-2xl overflow-hidden border border-neutral-100/60 p-4 space-y-3">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-full bg-neutral-200/60 animate-pulse" />
              <div className="space-y-1.5">
                <div className="h-3.5 w-24 bg-neutral-200/60 rounded animate-pulse" />
                <div className="h-2.5 w-16 bg-neutral-200/40 rounded animate-pulse" />
              </div>
            </div>
            <div className="grid grid-cols-2 gap-2">
              <div className="aspect-[4/3] rounded-xl bg-neutral-100 animate-pulse" />
              <div className="aspect-[4/3] rounded-xl bg-neutral-100 animate-pulse" />
            </div>
            <div className="h-4 w-3/4 bg-neutral-200/40 rounded animate-pulse" />
          </div>
        ))}
      </div>
    </div>
  );
}

// my_app/src/views/Community.vue
<template>
  <div class="community-page">
    <!-- 顶部导航 -->
    <header class="header">
      <div class="header-content">
        <button class="back-btn" @click="goBack">
          <span class="icon">←</span>
        </button>
        <h1 class="title">社区</h1>
        <button class="my-posts-btn" @click="goToMyPosts">
          <span class="icon">👤</span>
        </button>
      </div>
    </header>

    <!-- 页面内容 -->
    <div class="content">
      <!-- 标题区 -->
      <div class="page-header">
        <h2 class="page-title">广场</h2>
        <p class="page-subtitle">分享你的成功</p>
      </div>

      <!-- 加载中 -->
      <div v-if="loading" class="skeleton-list">
        <div v-for="i in 3" :key="i" class="skeleton-card">
          <div class="skeleton-user">
            <div class="skeleton-avatar"></div>
            <div class="skeleton-user-info">
              <div class="skeleton-name"></div>
              <div class="skeleton-time"></div>
            </div>
          </div>
          <div class="skeleton-images">
            <div class="skeleton-img"></div>
            <div class="skeleton-img"></div>
          </div>
          <div class="skeleton-text"></div>
        </div>
      </div>

      <!-- 错误状态 -->
      <div v-else-if="error" class="error-state">
        <p class="error-text">加载失败</p>
        <button class="retry-btn" @click="refresh">重试</button>
      </div>

      <!-- 空状态 -->
      <div v-else-if="posts.length === 0" class="empty-state">
        <p class="empty-text">暂无帖子</p>
        <p class="empty-desc">成为第一个分享成功的人</p>
      </div>

      <!-- 帖子列表 -->
      <div v-else class="post-list">
        <div
          v-for="(post, index) in posts"
          :key="post.id"
          class="post-card"
          @click="goToDetail(post.id)"
        >
          <!-- 用户信息 -->
          <div class="post-header">
            <div class="user-info">
              <div class="avatar">
                <img v-if="post.userAvatar" :src="post.userAvatar" :alt="post.userName" />
                <span v-else class="avatar-text">{{ post.userName?.charAt(0)?.toUpperCase() }}</span>
              </div>
              <div class="user-detail">
                <p class="user-name">{{ post.userName }}</p>
                <p class="post-time">{{ formatRelativeTime(post.createdAt) }}</p>
              </div>
            </div>
            <div class="amount-tag">
              {{ formatCurrency(post.withdrawAmount) }}
            </div>
          </div>

          <!-- 双图预览 -->
          <div class="post-images">
            <div class="image-wrapper">
              <img :src="post.platformScreenshot" alt="平台截图" loading="lazy" />
              <span class="image-label">平台</span>
            </div>
            <div class="image-wrapper">
              <img :src="post.receiptScreenshot" alt="收据截图" loading="lazy" />
              <span class="image-label">收据</span>
            </div>
          </div>

          <!-- 文字内容 -->
          <p v-if="post.content" class="post-content">{{ post.content }}</p>

          <!-- 互动栏 -->
          <div class="post-actions">
            <button class="action-btn" @click.stop="handleLike(post)">
              <span :class="['icon', post.isLiked ? 'liked' : '']">
                {{ post.isLiked ? '❤️' : '🤍' }}
              </span>
              <span :class="['count', post.isLiked ? 'liked' : '']">{{ post.likeCount }}</span>
            </button>
            <div class="action-btn">
              <span class="icon">💬</span>
              <span class="count">{{ post.commentCount }}</span>
            </div>
          </div>
        </div>

        <!-- 加载更多 -->
        <div v-if="hasMore" class="load-more">
          <span v-if="loadingMore">加载中...</span>
          <button v-else @click="loadMore">加载更多</button>
        </div>
      </div>
    </div>

    <!-- 浮动创建按钮 -->
    <button class="create-btn" @click="goToCreate">
      <span class="icon">+</span>
    </button>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { getPosts, likePost, type Post } from '@/api/community'

const router = useRouter()

// 状态
const loading = ref(true)
const error = ref(false)
const loadingMore = ref(false)
const posts = ref<Post[]>([])
const page = ref(1)
const pageSize = 10
const total = ref(0)

const hasMore = computed(() => posts.value.length < total.value)

// 加载帖子列表
const loadPosts = async (reset = false) => {
  try {
    if (reset) {
      page.value = 1
      posts.value = []
    }
    const currentPage = reset ? 1 : page.value
    const data = await getPosts(currentPage, pageSize)
    if (reset) {
      posts.value = data.list
    } else {
      posts.value = [...posts.value, ...data.list]
    }
    total.value = data.pagination.total
    page.value++
    error.value = false
  } catch (e) {
    console.error('Failed to load posts:', e)
    error.value = true
  } finally {
    loading.value = false
    loadingMore.value = false
  }
}

// 加载更多
const loadMore = () => {
  loadingMore.value = true
  loadPosts()
}

// 刷新
const refresh = () => {
  loading.value = true
  loadPosts(true)
}

// 点赞
const handleLike = async (post: Post) => {
  try {
    const result = await likePost(post.id)
    post.isLiked = result.liked
    post.likeCount = result.likeCount
  } catch (e) {
    console.error('Failed to like:', e)
  }
}

// 格式化相对时间
const formatRelativeTime = (dateStr: string) => {
  const diff = Date.now() - new Date(dateStr).getTime()
  const minutes = Math.floor(diff / 60000)
  if (minutes < 1) return '刚刚'
  if (minutes < 60) return `${minutes}分钟前`
  const hours = Math.floor(minutes / 60)
  if (hours < 24) return `${hours}小时前`
  const days = Math.floor(hours / 24)
  return `${days}天前`
}

// 格式化金额
const formatCurrency = (amount: number) => {
  return `$${amount.toFixed(2)}`
}

// 导航
const goBack = () => router.back()
const goToDetail = (id: number) => router.push(`/community/${id}`)
const goToMyPosts = () => router.push('/community/my')
const goToCreate = () => router.push('/community/create')

onMounted(() => {
  loadPosts()
})
</script>

<style scoped>
.community-page {
  min-height: 100vh;
  background: linear-gradient(to bottom, #f0f9ff, #fff, #fafafa);
}

.header {
  position: sticky;
  top: 0;
  z-index: 30;
  background: rgba(250, 250, 248, 0.95);
  backdrop-filter: blur(20px);
  border-bottom: 1px solid rgba(0, 0, 0, 0.04);
}

.header-content {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 56px;
  padding: 0 16px;
}

.back-btn,
.my-posts-btn {
  width: 40px;
  height: 40px;
  border: none;
  background: transparent;
  cursor: pointer;
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.back-btn:hover,
.my-posts-btn:hover {
  background: rgba(0, 0, 0, 0.05);
}

.back-btn .icon,
.my-posts-btn .icon {
  font-size: 20px;
}

.title {
  font-size: 18px;
  font-weight: 600;
  color: #1a1a1a;
}

.content {
  padding: 16px;
  padding-bottom: 120px;
}

.page-header {
  margin-bottom: 16px;
}

.page-title {
  font-size: 20px;
  font-weight: 700;
  color: #1a1a1a;
}

.page-subtitle {
  font-size: 14px;
  color: #666;
  margin-top: 4px;
}

/* 骨架屏 */
.skeleton-list {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.skeleton-card {
  background: #fff;
  border-radius: 16px;
  padding: 16px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.04);
}

.skeleton-user {
  display: flex;
  gap: 12px;
  margin-bottom: 12px;
}

.skeleton-avatar {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  background: #e5e5e5;
  animation: pulse 1.5s infinite;
}

.skeleton-user-info {
  flex: 1;
}

.skeleton-name {
  width: 100px;
  height: 16px;
  background: #e5e5e5;
  border-radius: 4px;
  margin-bottom: 6px;
  animation: pulse 1.5s infinite;
}

.skeleton-time {
  width: 60px;
  height: 12px;
  background: #e5e5e5;
  border-radius: 4px;
  animation: pulse 1.5s infinite;
}

.skeleton-images {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 8px;
  margin-bottom: 12px;
}

.skeleton-img {
  aspect-ratio: 4/3;
  border-radius: 12px;
  background: #e5e5e5;
  animation: pulse 1.5s infinite;
}

.skeleton-text {
  width: 75%;
  height: 14px;
  background: #e5e5e5;
  border-radius: 4px;
  animation: pulse 1.5s infinite;
}

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.5; }
}

/* 错误/空状态 */
.error-state,
.empty-state {
  text-align: center;
  padding: 60px 20px;
}

.error-text,
.empty-text {
  font-size: 16px;
  color: #666;
}

.empty-desc {
  font-size: 14px;
  color: #999;
  margin-top: 8px;
}

.retry-btn {
  margin-top: 16px;
  padding: 10px 24px;
  background: #3b82f6;
  color: #fff;
  border: none;
  border-radius: 8px;
  cursor: pointer;
}

/* 帖子卡片 */
.post-list {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.post-card {
  background: #fff;
  border-radius: 16px;
  padding: 16px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.04);
  border: 1px solid rgba(0, 0, 0, 0.04);
  cursor: pointer;
  transition: transform 0.2s;
}

.post-card:active {
  transform: scale(0.99);
}

.post-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 12px;
}

.user-info {
  display: flex;
  align-items: center;
  gap: 12px;
}

.avatar {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  background: linear-gradient(135deg, #dbeafe, #bfdbfe);
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
}

.avatar img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.avatar-text {
  font-size: 14px;
  font-weight: 600;
  color: #2563eb;
}

.user-detail {
  display: flex;
  flex-direction: column;
}

.user-name {
  font-size: 14px;
  font-weight: 600;
  color: #1a1a1a;
}

.post-time {
  font-size: 12px;
  color: #999;
  display: flex;
  align-items: center;
  gap: 4px;
}

.amount-tag {
  padding: 6px 12px;
  border-radius: 20px;
  background: linear-gradient(135deg, #eff6ff, #dbeafe);
  border: 1px solid rgba(59, 130, 246, 0.2);
  font-size: 12px;
  font-weight: 600;
  color: #2563eb;
}

.post-images {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 8px;
  margin-bottom: 8px;
}

.image-wrapper {
  position: relative;
  border-radius: 12px;
  overflow: hidden;
  aspect-ratio: 4/3;
  background: #f5f5f5;
}

.image-wrapper img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.image-label {
  position: absolute;
  bottom: 6px;
  left: 6px;
  padding: 2px 8px;
  border-radius: 6px;
  background: rgba(0, 0, 0, 0.5);
  color: #fff;
  font-size: 10px;
}

.post-content {
  font-size: 14px;
  color: #666;
  line-height: 1.5;
  margin-bottom: 12px;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.post-actions {
  display: flex;
  align-items: center;
  gap: 24px;
  padding-top: 12px;
  border-top: 1px solid #f5f5f5;
}

.action-btn {
  display: flex;
  align-items: center;
  gap: 6px;
  background: none;
  border: none;
  cursor: pointer;
  color: #999;
}

.action-btn .icon {
  font-size: 18px;
}

.action-btn .count {
  font-size: 14px;
}

.action-btn .liked {
  color: #ef4444;
}

/* 加载更多 */
.load-more {
  text-align: center;
  padding: 20px;
}

.load-more button {
  background: none;
  border: none;
  color: #666;
  cursor: pointer;
  font-size: 14px;
}

/* 浮动创建按钮 */
.create-btn {
  position: fixed;
  bottom: 100px;
  right: 20px;
  width: 56px;
  height: 56px;
  border-radius: 50%;
  background: #3b82f6;
  color: #fff;
  border: none;
  box-shadow: 0 6px 24px rgba(59, 130, 246, 0.4);
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 40;
}

.create-btn .icon {
  font-size: 28px;
}

.create-btn:hover {
  transform: scale(1.1);
}
</style>
